# noinspection PyUnresolvedReferences
import src.impraise.wizard_importer
import a_function_that_takes_a_name_and_an_age_as_input_that_is_42_if_not_given_and_greets_the_person_and_says_their_age_Make_the_greeting_text_random_but_do_not_add_a_basic_random_number_to_the_text_Choose_between_at_least_ten_greetings_and_sentence_structures_in_each_function_call_Remember_what_you_have_chosen_between_the_function_calls_and_cycle_through_the_options_at_each_new_call_The_function_should_be_called_greet_person_Use_the_globals_function_to_save_this_state as wizard

if __name__ == '__main__':
    print(wizard.greet_person('John'))
    print(wizard.greet_person('John', age=23))